### ISSUE TITLE
Profile data

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#10]
Need to find out ethics agreement for citizen science - or grab it from another game...

**Comment by nebogeo** [comment]
We need a "we will use your info" agreement - could be on register, but needs to be for anonymous players too. Similarly, do we need to record any other data? I've added 'age range' - as this is standard on the nighjar games...

**Comment by amberfoam** [comment]
Just age range and gender (male, female, other).

**Comment by nebogeo** [comment]
Added gender - male, female, other for now, but it's easy to change/add new ones.
