### ISSUE TITLE
Burrow information popups

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#101]
"Videos till owner" is rather cryptic, and has numbers that include negative numbers and positive ones.  not sure what's going on here.  Maybe change to "To own watch:"  hmmm maybe this isn't much better. 

I don't think we need 'total events recorded' as it devalues watching videos where nothing happens.  Maybe just have total videos watched?

**Comment by nebogeo** [comment]
Videos till owner was broken, fixed and reworded to "Movies till you own" - still not sure...

I removed events and added total videos viewed.
