### ISSUE TITLE
Videos not playing properly on Safari??

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#102]
I have two colleagues in the same office one using a windows machine and one on a mac laptop.  On the mac laptop, the site works fine, but the video stops for long periods then moves a few frames then stops.  I tried both machines simultaneously, and only the Mac had the problem.  We tried different burrows so I don't think it was a problem with one video.

The mac was running on the wifi, so it's not 100% certain the problem was the browser (Safari).

I can imagine this is a tricky problem to solve.

**Comment by nebogeo** [comment]
Seems ok in safari here, but the first video I played (one of the tutorials) did this and then started working ok. So it could be a downloading problem, but it needs testing...

**Comment by Pleiotrope** [comment]
My colleague tried firefox on the same machine and didn't have the same problem, so it seems like it was Safari.

However he did get this warning message:

![image](https://cloud.githubusercontent.com/assets/14270809/13007850/cc0c2a00-d18a-11e5-9c8c-90e1eedf60bf.png)

**Comment by nebogeo** [comment]
That's interesting, is it still a problem? Firefox seems happy here but it might have been an exeter IT problem (with the server certificates)

**Comment by Pleiotrope** [comment]
Not sure if this is still a problem, if it's working on firefox at your end, I think we should move on...
