### ISSUE TITLE
Some feedback following event logging clicks

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#104]
Multiple independent feedback indicating that we need some feedback to show a click ha actually been recognised by the system.  Suggestions include:

Perhaps the button clicked could morph for a second 
A little red flash on the border of the button that then fades

**Comment by amberfoam** [comment]
other options: sound/haptic/sticky buttons/marker in timeline

**Comment by Pleiotrope** [comment]
Sure, anything really but we do need some feedback from clicks

**Comment by nebogeo** [comment]
New plan - put the small event timeline indicators back in (only for the current view) and make the buttons flash when they are clicked on. Try it for a bit, if the timeline indicators are confusing we can easily remove them.

**Comment by Pleiotrope** [comment]
lovin it
