### ISSUE TITLE
Require a minimum number of videos to be watched before a house can be built?

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#106]
People value things they have to work for (a bit)

Maybe we should require people to watch at least 10 videos before they can build a house?

**Comment by nebogeo** [comment]
Not sure about this, as it's something which is going to be quite non-linear - as it will get harder over time to build houses.

**Comment by Pleiotrope** [comment]
I realise it will get harder, which I think is good, but I'd rather we start off requiring 10 videos rather than 1?

**Comment by nebogeo** [comment]
Sure - done.

**Comment by amberfoam** [comment]
Really not sure about this one - I think we need to grab people as quickly as we can. In terms of providing an incentive to keep playing, the competitive element seemed to work well when people were trialling it. I think if someone goes in, watches a few videos, and gets bored, there is nothing to keep them there if we set a minimum number of videos - if they get a house, they are more likely to keep playing. It is also just one more thing we'd have to explain in the tutorial, which is already lengthy.

**Comment by nebogeo** [comment]
I've removed this for a bit and see how it goes...
