### ISSUE TITLE
IDing other crickets

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#108]
Group member said: How do you record the tag of 'another cricket?  Must you delete the last one or does this change the ID of the primary cricket?

Is it possible for 'Another cricket' to pause the video and bring up a dialogue box that requests the ID of the other cricket?

**Comment by nebogeo** [comment]
There are lots of ambiguities to this feature, and too many situations to try and cover while not putting people off. One thing to consider is that a new 'IDing event' is created each time you submit the dialog - there is no internal concept of "primary cricket", so it's quite possible to ID multiple crickets as it is. We can scan the movies for ones with multiple IDs for example. It might be worth mentioning this in the tutorial.
