### ISSUE TITLE
abort/erase/start again button

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#109]
Several people commented that they really didn't like knowing they'd made a mistake and not being able to do anything about it.  

I realise that editing entries is too complex, but if we had a "RESTART" button I think this would be a straightforward way to allow people to do that.  Ideally this would either erase the data they collected prior to pressing abort, or would place a flag in the database file that would allow the data to be erased subsequently.

I think this would be a major improvement.

**Comment by nebogeo** [comment]
Needs a restart/undo icon in the same style as the play/pause - we can possibly put this to the right of the timeline on the video?

**Comment by amberfoam** [comment]
Image done

**Comment by nebogeo** [comment]
Added - inserts a "redo" event in the event stream for the player/movie so we can filter out preceding ones in future.
