### ISSUE TITLE
Overview of cricket tales progress as a whole 

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#115]
Rolando comments: I think an extra section giving some general information about the findings up to date for the whole meadow, would be nice for players. For instance, how many males and females have been found, who is the most successful individual, how many burrows that cricket uses, and also info about watchers, what’s the maximum number of videos watched by someone, how many people is contributing, etc.

I think something along these lines, so that regular contributors have a sense that the project as a whole is making progress would be very welcome - it doesn't have to be all the above

**Comment by amberfoam** [comment]
Equivalent details to the daily cricket report emails could go on the about page.

**Comment by nebogeo** [comment]
Just looking at this now - yes to general stats on players, videos available, watched etc. The information on crickets themselves is harder, or even not available in some cases. We're no longer linking events to the individual crickets as it's costly to do and not used anywhere else in the game.
We can have things like number of unique crickets ID'ed or burrow with the most singing...

**Comment by Pleiotrope** [comment]
Yes, let's do the things that are easy and forget the things that are hard...
