### ISSUE TITLE
Compatibility with android

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#117]
Cricket tales doesn't show videos on my Android phone (running Android 5.0 Lollipop).  

I realize that getting compatibility across all platforms is probably not possible, but figured I should flag this nevertheless.

**Comment by nebogeo** [comment]
I think this is the same problem as ipad, and yep we should have it running on both iOS and android

**Comment by nebogeo** [comment]
This should be fixed, or at least it will be when the script's finished making 70,000 thumbnails from the first frame of each video :) Also should have fixed iPad but will need to test that to make sure...
