### ISSUE TITLE
Add age range buttons

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#118]

**Comment by amberfoam** [comment]
Suggest:
14 or under
15 to 24
25 to 34
35 to 44
45 to 54
55 to 64
65 or over
decline to answer

**Comment by nebogeo** [comment]
Ah - while you wrote that I added the categories from camo games:

rather not say
<10
10-15
16-35
36-50

> 50

**Comment by amberfoam** [comment]
Sure your ranges ar fine, probably better - was just trying to be helpful!

**Comment by Pleiotrope** [comment]
I see newspaper headlines about old people taking part, but for that we need a bigger range.

If it's not a lot of work, could we have something closer to Amber's suggestion?

**Comment by nebogeo** [comment]
over 50's on the list - github just formatted it weirdly
