### ISSUE TITLE
Movie page: The option of clicking directly on the video image for playback or pause works only sporadically.

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#122]

**Comment by nebogeo** [comment]
Do we want this to happen at all? Presumably (this was from Rolando's doc) this is after burrow and cricket have been clicked on... I think only the buttons should play/pause.

**Comment by amberfoam** [comment]
I don't think it should happen at all - just play and pause buttons (toggled and bigger ones!)

**Comment by Pleiotrope** [comment]
Yes, I'm not sure what's going on with this - it was from R's comments, but if it's not supposed to happen,  there probably isn't a problem, so let's forget it....
