### ISSUE TITLE
When is a movie "finished"?

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#125]
We don't have enough disk space for all the movies (and we might want to add more in the future) so there is a mechanism in place to recycle it, by deleting the files belonging to "finished" movies (but not the database records) so new ones can be created.

I would suggest when it contains events (incl no cricket records) made by n people, where n is somewhere between 2 and 10 :)

**Comment by Pleiotrope** [comment]
This sounds like a good plan.  Being able to change the n easily will be very useful.  I think in the first instance, we should make n at least 3 so we get some measure of repeatability.  Let's start with that...

**Comment by nebogeo** [comment]
n is now 3, and the new report specifies how many videos are complete (currently 3!)
