### ISSUE TITLE
iPhone burrow video doesn't play fullscreen

### ISSUE THREAD

**Issue by sargentfrancesca** [nebogeo/cricket-tales#126]

**Comment by sargentfrancesca** [comment]
going to try 
a. detecting device in django, request.device['device'] in views & pass to context, or .mobile decorator can be added for all mobile devices using minidetector
b. implementing this workaround https://github.com/newshorts/InlineVideo for iPhones
👍

**Comment by sargentfrancesca** [comment]
http://stanko.github.io/html-canvas-video-player/

**Comment by nebogeo** [comment]
what state is this in - I see some new files...

**Comment by sargentfrancesca** [comment]
still not resolved, focusing on other issues so can give full attention

**Comment by sargentfrancesca** [comment]
Still looking at this - I have found a good library to support this (the minified one!), it has basic functionality, which is great. I am emulating the iPhone user agent within the Safari browser, however for some reason, today I absolutely cannot access localhost via my iPhone, aargh, so haven't been able to test that it actually works without fullscreen... it does that sometimes. In terms of the library, I can get it to autoplay, but when using buttons, the video always pauses immediately after a play event is fired. Thought originally that this was a clash with the existing js, so separated that out and made only loaded by non-iPhone browser, but problem still persists. Lunch, then more fiddling!

**Comment by nebogeo** [comment]
Sounds like a nightmare! On iphone, are there choices for browsers? We can fall back to recommending chrome if needbe...

**Comment by sargentfrancesca** [comment]
Yes, there are, generally I use Chrome. However, same problems with alternate browsers forcing fullscreen and not being able to connect to localhost… Have been using Safari as the web inspector works with my mac!

Francesca Sargent
Computing Development Officer
Centre for Ecology and Conservation
University of Exeter

On 7 Apr 2016, at 15:15, dave griffiths <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds like a nightmare! On iphone, are there choices for browsers? We can fall back to recommending chrome if needbe...

**Comment by amberfoam** [comment]
From Tom: "Regarding the iphone, I think we probably shouldn't spend more time on this for a small proportion of users, and the danger that a new OS comes out in 3 months and we have to start again."
