### ISSUE TITLE
Add videos for cricket movements to training page - 2 videos arrived, 2 remaining

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/cricket-tales#137]

**Comment by amberfoam** [comment]
Two videos sent, so can put these ones in. Waiting on remaining two.

**Comment by nebogeo** [comment]
ah yes, sorry for superfluous email

**Comment by amberfoam** [comment]
All videos have arrived - could do with editing to make shorter where possible e.g. ~10 seconds max.
