### ISSUE TITLE
make a button with a cricket on it

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#140]

**Comment by sargentfrancesca** [comment]
as an event?

**Comment by amberfoam** [comment]
nah for the middle one on the front page - so you don't have to worry about it sticking/resizing etc can just treat it as normal button. That sound sensible?

**Comment by sargentfrancesca** [comment]
OHH I understand, yes!

**Comment by nebogeo** [comment]
buttons need to resize quite a bit, so fixed with code...
