### ISSUE TITLE
House builder doesn't appear at right time

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/cricket-tales#156]
Should appear when go back to map. At the moment nothing happens when go back to map, but if go out of game, then back in (e.g. continue playing), it then comes up before the map does which is a bit confusing.

**Comment by nebogeo** [comment]
It scans for housebuilding once a minute, so it can take a while but doesn't require going out and back in again.

**Comment by nebogeo** [comment]
When is the 'right time' actually? 
Do we need a new button that flashes in the menu bar on the map page when it's ready?

**Comment by amberfoam** [comment]
Instead of scanning once a minute, scan before going back to map? Or at end of each video just for that burrow?

**Comment by nebogeo** [comment]
Soo much better!
