### ISSUE TITLE
tutorial text is wrong

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#164]
since we changed the button layout, the text needs updating (and final checking)

**Comment by amberfoam** [comment]
Text checked and edits sent over via email.

**Comment by nebogeo** [comment]
Just to check - when not logged in, the text:
"On the next page you'll see your meadow. Click on a cricket burrow to start."
Is changed to:
"If you register you can see the your meadow, where you can build houses for the crickets!"

**Comment by amberfoam** [comment]
Yup that makes sense...

**Comment by nebogeo** [comment]
Updated, also a load of formatting stuff...
