### ISSUE TITLE
check data is correct

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#166]
The data can now be downloaded from the admin interface ("Download CSV data" link under the title). Please check this is correct! This is the result of processing the events to get the source movie and start time/frame - the event times are seconds offset from this.

**Comment by Pleiotrope** [comment]
I've mislaid my administrator login - sorry.  Been searching for days to avoid this embarassing admission - can you supply a login and password reminder?

**Comment by nebogeo** [comment]
I'm not sure you had admin rights recently, looking at the user list...! There are various users with your email, so I gave them all admin rights :) The URL you need is: http://cricket-tales.exeter.ac.uk/admin/

**Comment by Pleiotrope** [comment]
Rolando is taking a look at the data file
