### ISSUE TITLE
Arrives frame button missing

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/cricket-tales#169]

**Comment by nebogeo** [comment]
From where? The movie page?!

**Comment by amberfoam** [comment]
Yep - is an extra button that Tom wanted - we missed it and I only noticed yesterday when we were sent the video for this. Can move 'another cricket' button down and next to ID button maybe?

**Comment by nebogeo** [comment]
Ok - and change the ID button into a normal one?

**Comment by amberfoam** [comment]
I think it's ok as it is - they want ID info so might make sense that the button stands out a bit?

**Comment by nebogeo** [comment]
done, and not as painful as I imagined...
