### ISSUE TITLE
ipad - Video page: long load time and kept skipping back to the beginning

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/cricket-tales#181]

**Comment by amberfoam** [comment]
"When the video doesn't load on my iPad, it looks like it goes back a bit to try again, then maybe goes ahead one sec and then back again"

**Comment by amberfoam** [comment]
"It works ok for a second, then it starts going really slow frame by frame then the video stops, and the pink dot jumps back, then goes frame by frame again, then it might go for a second, but then the same thing keeps happening"

**Comment by nebogeo** [comment]
seems to be ok after update - need to keep this in mind...
