### ISSUE TITLE
Leadership board?

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/cricket-tales#187]
Just putting this here to see how many people want this.
1. "leader boards and overall stats on whose ID the most crickets, total number of hours watching"

**Comment by Pleiotrope** [comment]
This is a tricky one - I think probably we don't want this because it may encourage people to watch videos quickly in order to up their stats.  Ploughing through the data to remove people doing a shoddy job manually will be too time consuming.  I think we try without a public leaderboard for now?
