### ISSUE TITLE
Registration - limit username length

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/cricket-tales#189]

**Comment by nebogeo** [comment]
I don't know if it's better practice to limit the display of the name, otherwise it gets harder to have unique ones. Is this only a problem in the story speech bubbles?

**Comment by amberfoam** [comment]
Speech bubbles and also potentially a way to stop people putting their email in there.

**Comment by nebogeo** [comment]
Checking and restricting to 10 characters in speech bubble display
