### ISSUE TITLE
Movie page: id button starts video playing 

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#22]
problem in first stage...

**Comment by sargentfrancesca** [comment]
this can be addressed with state machine?

**Comment by nebogeo** [comment]
twas my thinking too :)

**Comment by sargentfrancesca** [comment]
also - had previously set the ID button to appear after the first click events (cricket start, burrow) - not sure if this is still needed, or better to have ID appearing from start.

**Comment by amberfoam** [comment]
It's fine just to be there all the time - is a bit weird having one button appear from nowhere while the others are always there
