### ISSUE TITLE
Server: Can't git pull again?!

### ISSUE THREAD

**Issue by sargentfrancesca** [nebogeo/cricket-tales#27]
Can't git pull or sudo git pull in /var/www/cricket-tales

**Comment by nebogeo** [comment]
should just be git pull, are you a member of the www-data club still?

**Comment by sargentfrancesca** [comment]
yep still part of the gang:
https://www.dropbox.com/s/jd8es4396ywg4nk/Screenshot%202015-12-10%2011.25.45.png?dl=0

looking at SSH now

**Comment by nebogeo** [comment]
just pulled it - be in a mo

**Comment by nebogeo** [comment]
currently doing 
$ sudo chown www-data:www-data .git -R
fixes it

**Comment by nebogeo** [comment]
seem to have this fixed now...
