### ISSUE TITLE
events in video timeline

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#40]
In an earlier version, events recorded by users created a marker on the video timeline.  I thought this was a nice way to show that the information had been recorded, but it seems to have been lost from the current version

**Comment by nebogeo** [comment]
I think the problem was that it can be confusing, people might want to edit them which would add more complexity than it's worth - it would be good to give feedback though, worth thinking about ways to do that (perhaps a counter?)

**Comment by Pleiotrope** [comment]
OK I see the point about them causing stress as they can't be edited.  I think an alternative 'events recorded' counter, and/or possibly a bit of feedback when an event is successfully logged would be useful.

**Comment by amberfoam** [comment]
How about the pink timeline marker just leaves a similar sized green dot on the timeline when a button is clicked.

**Comment by Pleiotrope** [comment]
Yes, we had this before, but Dave got rid of it for the reasons above, which do seem like legitimate concerns, I can imagine people fretting over trying to edit the dots.  However, I guess this has to be balanced against their value as feedback...

**Comment by nebogeo** [comment]
The answer seems to be fading dots!

**Comment by Pleiotrope** [comment]
Yes, that sounds neat, let's try that
