### ISSUE TITLE
Prompting for ID

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#43]
ID is a useful bit of data for us.  We could prompt people who have not entered an ID and who then choose to click on the cricket at the end of the video, to ask them to enter the cricket's ID, with the added options of 'Tagged, but unclear' or 'no tag'

**Comment by nebogeo** [comment]
I think there are enough prompts (and by the end the cricket may not be visible). I'm going to close this for the moment, and see if we need special enticements for this - e.g. a top ten list of people who've IDed the most crickets.
