### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/cricket-tales#46]
At the end when all the text has been finalised.

**Comment by nebogeo** [comment]
@Pleiotrope do you have anyone in mind we could recruit for the spanish translations?

**Comment by Pleiotrope** [comment]
Yes, Rolando! Cc-d.  Just send him the text and he'll translate it, or let us know if there's a more efficient approach...

Best

Tom

On Fri, Apr 1, 2016 at 7:20 AM -0700, "dave griffiths" notifications@github.com wrote:

@Pleiotrope do you have anyone in mind we could recruit for the spanish translations?

---

**Comment by nebogeo** [comment]
super - although quite some changes yet on the tutorial etc...
