### ISSUE TITLE
Provide guidance on what entering a burrow means

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#95]
I think we need to make a clearer statement on whether a cricket enters a burrow to avoid people being paralysed by indecision over this (or waste a lot of time on it).  Something like:  "Enters burrow (cricket disappears completely from your view), Leaves burrow (cricket that was out of sight down a burrow re-emerges). These events often happen in quick succession, if in doubt go with your first decision, it's not critical to be precise over this particular behaviour..."

**Comment by nebogeo** [comment]
I've tweaked the tutorial text for these buttons...
