### ISSUE TITLE
Limit number of words that can be added to comments box

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#96]
Maybe limit this to 50 words or 250 characters or something?  We don't want people writing essays.

Importance rating in my view 3 (1 = not very, 5 = essential)

**Comment by nebogeo** [comment]
To some extent we need to see how people use elements like this, so I think pre-restricting it is the wrong approach and makes it feel like the wrong kind of online form. At the end of the day, we can simply filter out all the long ones!

**Comment by Pleiotrope** [comment]
Sure, point taken
