### ISSUE TITLE
Finding burrows you've been studying

### ISSUE THREAD

**Issue by Pleiotrope** [nebogeo/cricket-tales#98]
It is very hard to find a burrow where you have already watched some video.  We need something to help people return to the same burrow that they've studied previously

**Comment by nebogeo** [comment]
I've added the flags to denote this, small for ones you've contributed to the burrow and large for ones with houses you've built. Possibly they need to be more contrasty. 

Adding the username is going to be a major PITA (spent quite a while trying to position/resize text and it's a no-goer). So can we change the long flag so it has "Built by YOU!" in the image instead? (and we'll need a translated version I guess).

**Comment by Pleiotrope** [comment]
I think flags could work "Built by YOU" is fine with me or "Yours!" If we think this wouldn't need translating

**Comment by nebogeo** [comment]
We will translate this - it's more a case of remembering to do it as it'll need a new image made. This is in now btw, so closing!

**Comment by Pleiotrope** [comment]
Great and 'my house' works well, just seen it on the map
